env: production
debug: false
postgres_dsn: postgres://test:test@localhost:5432/portfolio_balance?sslmode=disable
postgres_conn_limit: 10
sentry:
  enabled: false
kafka:
  user: adminscram
  password: admin-secret-512
  brokers:
    - 127.0.0.1:9093
  group: data_point_group
  topic: transaction
  start_offset: 0
  min_bytes: 78
  max_bytes: 2_000_000
  max_wait: 3s
pending_kafka_topic: data_point_pending
data_point_consumer:
  workers_count: 1
  bucket_size: 100_000
  bucket_wait_time: 3s
  message_rps: 200
  message_burst: 1_000
  data_point_timestamp: 15m
  insert_pending_enabled: true
bulkinsert_fallback: raise_error
